export enum Actions {
  ADDGOODSINCART = "ADDGOODSINCART",
  DECREASE_GOODSINCART = "DECREASE_GOODSINCART",
  DELETE_FOOD_FROM_CART = "DELETE_FOOD_FROM_CART",
  TOGGLE_BURGER = "TOGGLE_BURGER",
  CLOSE_BURGER = "CLOSE_BURGER",
  LOGOUT = "LOGOUT",
  SET_USER = "SET_USER",
  SET_GOODS = "SET_GOODS",
  INC_GOODS_LOCAL = "INC_GOODS_LOCAL",
  DEC_GOODS_LOCAL = "DEC_GOODS_LOCAL",
  DELETE_FOOD_FROM_CART_LOCAL = "DELETE_FOOD_FROM_CART_LOCAL",
  SET_LOADING = "SET_LOADING",
}
